input("give me a word!")
print("lorry!")
input("give me a second word!")
print("deoxyribonucleic?")
print()
input("great, now your favourite number?")
print("42")
input('and your second-favourite number?')
print(1)
print()
print("whew! wasn't that fun?")
